import { Characters, ICharacter, TCharacters } from "../Characters";
import {
    Alani_Hlaar,
    Amber_Hlaar,
    Annie_Hlaar,
    Azmah,
    Cica_Hlaar,
    Emily_Hlaar,
    Gawen_Hlaar,
    Ginger_Hlaar,
    Gwain_Hlaar,
    Haru_Hlaar,
    Hira_Hlaar,
    Julie_Hlaar,
    Kimi_Hlaar,
    Lael_Caerl,
    Lin_Hlaar,
    Lola_Hlaar,
    Marnie_Bryne,
    Meila_Hlaar,
    Mika_Hlaar,
    Nuala_Hlaar,
    Risaria,
    Robin_Hemingway,
    Rosie_Hlaar,
    Saya_Hlaar,
    Seori,
    Shilli_Akehurst,
    Tana_Hlaar,
    Tarluk,
    Val_Hlaar,
    Yuela_Hlaar,
    Yumi_Hlaar,
    Zeenel_Hlaar,
} from "./index";

const CharacterList: { [key in TCharacters]: ICharacter } = {
    [Characters.Alani_Hlaar]: Alani_Hlaar,
    [Characters.Amber_Hlaar]: Amber_Hlaar,
    [Characters.Annie_Hlaar]: Annie_Hlaar,
    [Characters.Azmah]: Azmah,
    [Characters.Cica_Hlaar]: Cica_Hlaar,
    [Characters.Emily_Hlaar]: Emily_Hlaar,
    [Characters.Gawen_Hlaar]: Gawen_Hlaar,
    [Characters.Ginger_Hlaar]: Ginger_Hlaar,
    [Characters.Gwain_Hlaar]: Gwain_Hlaar,
    [Characters.Haru_Hlaar]: Haru_Hlaar,
    [Characters.Hira_Hlaar]: Hira_Hlaar,
    [Characters.Julie_Hlaar]: Julie_Hlaar,
    [Characters.Kimi_Hlaar]: Kimi_Hlaar,
    [Characters.Lael_Caerl]: Lael_Caerl,
    [Characters.Lin_Hlaar]: Lin_Hlaar,
    [Characters.Lola_Hlaar]: Lola_Hlaar,
    [Characters.Marnie_Bryne]: Marnie_Bryne,
    [Characters.Meila_Hlaar]: Meila_Hlaar,
    [Characters.Mika_Hlaar]: Mika_Hlaar,
    [Characters.Nuala_Hlaar]: Nuala_Hlaar,
    [Characters.Risaria]: Risaria,
    [Characters.Robin_Hemingway]: Robin_Hemingway,
    [Characters.Rosie_Hlaar]: Rosie_Hlaar,
    [Characters.Saya_Hlaar]: Saya_Hlaar,
    [Characters.Seori]: Seori,
    [Characters.Shilli_Akehurst]: Shilli_Akehurst,
    [Characters.Tana_Hlaar]: Tana_Hlaar,
    [Characters.Tarluk]: Tarluk,
    [Characters.Val_Hlaar]: Val_Hlaar,
    [Characters.Yuela_Hlaar]: Yuela_Hlaar,
    [Characters.Yumi_Hlaar]: Yumi_Hlaar,
    [Characters.Zeenel_Hlaar]: Zeenel_Hlaar,
};
export default CharacterList;
