import {
    Characters,
    ICharacter,
    PairCharacters,
    TCharacters,
} from "content/characters/Characters";

type TAllCharactersLayout = (TCharacters | { [key: string]: TCharacters[] })[];

export const AllCharactersLayout: TAllCharactersLayout = [
    {
        [PairCharacters.AlaniAndAnnieHlaar]: [
            Characters.AlaniHlaar,
            Characters.AnnieHlaar,
        ],
    },
    Characters.AmberHlaar,
    Characters.Ayenda,
    Characters.Azmah,
    Characters.CelineHlaar,
    Characters.CholeHlaar,
    Characters.CicaHlaar,
    Characters.ElalieHlaar,
    Characters.EmilyHlaar,
    Characters.EricaArklight,
    Characters.Esfir,
    Characters.FanaaHlaar,
    Characters.FylaeHlaar,
    {
        [PairCharacters.GawenAndGwainHlaar]: [
            Characters.GawenHlaar,
            Characters.GwainHlaar,
        ],
    },
    Characters.Ghan,
    Characters.GingerHlaar,
    Characters.HaruHlaar,
    Characters.HiraHlaar,
    Characters.IsisBrooks,
    Characters.JulieHlaar,
    Characters.KatyHlaar,
    Characters.KimiHlaar,
    Characters.LaelCaerl,
    Characters.LeiwaHlaar,
    Characters.LilyHlaar,
    Characters.LinHlaar,
    Characters.LolaHlaar,
    Characters.MarnieBryne,
    Characters.MeilaHlaar,
    Characters.Miikeeno,
    Characters.MikaHlaar,
    Characters.NaamahHlaar,
    Characters.Nish,
    Characters.NualaHlaar,
    Characters.Rika,
    Characters.Risaria,
    Characters.RobinHemingway,
    Characters.RosieHlaar,
    Characters.SayaHlaar,
    Characters.ScarletHlaar,
    Characters.Seori,
    Characters.ShadiHlaar,
    Characters.ShilliAkehurst,
    Characters.TanaHlaar,
    Characters.Tarluk,
    Characters.TrevanaArklight,
    Characters.ValHlaar,
    Characters.Vorix,
    Characters.YuelaHlaar,
    Characters.YumiHlaar,
    Characters.ZeenelHlaar,
    Characters.ZildaHlaar,
    Characters.ZumiHlaar,
];
